version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    restart: always
    environment:
      - POSTGRES_DB_USER=postgres
      - POSTGRES_DB_PSW=admin
      - SERVICE_POSTGRES_SERVICE_HOST=db
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - database:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=courses

volumes:
  database:
